{% set name = "dist-s1" %}
{% set version = "0.0.4" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dist_s1-{{ version }}.tar.gz
  sha256: 7053be9b0846615917b9c4a465b596163c4e999a2cd7e9024d4b1fbf1740dd18

build:
  entry_points:
    - dist-s1 = dist_s1.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - asf_search
    - backoff
    - click
    - dem_stitcher
    - dist_s1_enumerator
    - distmetrics
    - geopandas
    - numpy
    - pandas
    - pydantic
    - tile_mate >=0.0.12
    - pyyaml
    - rasterio
    - ruff
    - scipy

test:
  imports:
    - dist_s1
  commands:
    - pip check
    - dist-s1 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opera-adt/dist-s1
  summary: The workflow to generate the DIST-S1 product
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - richw7185
    - cmarshak
    - taliboliver
