{% set name = "dist-s1" %}
{% set version = "2.0.14" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/b9/76/e5d809a1e40ccdbb6e91bf80b5baa600091172d209abb706a39ec8e0965d/dist_s1-{{ version }}.tar.gz
  sha256: d8ea4f4c0cba45c91ff30de83fb695c4c30dbf157725ae3b75514a55debb63d5

build:
  entry_points:
    - dist-s1 = dist_s1.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - asf_search
    - backoff
    - click
    - dem_stitcher
    - dist_s1_enumerator
    - distmetrics >=0.0.10
    - geopandas
    - numpy
    - pandas
    - pydantic
    - tile_mate >=0.0.12
    - pyyaml
    - rasterio >=1.4.0
    - ruff
    - scipy

test:
  imports:
    - dist_s1
  commands:
    - pip check
    - dist-s1 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opera-adt/dist-s1
  summary: The workflow to generate the DIST-S1 product
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - richw7185
    - cmarshak
    - taliboliver
